USE SUCOS_VENDAS;

select tp.sabor, nf.DATA_VENDA, INF.QUANTIDADE FROM
tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = inf.numero;

/*QUANTIDADE VENDIDA POR SABOR ANO 2016 */
select tp.sabor, year(nf.DATA_VENDA) as ano, sum(INF.QUANTIDADE) as QUANTIDADE FROM
tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = inf.numero
WHERE year(nf.DATA_VENDA) = 2016
GROUP BY tp.sabor, year(nf.DATA_VENDA)
ORDER BY Sum(INF.QUANTIDADE) DESC;


select year(nf.DATA_VENDA) as ANO, sum(INF.QUANTIDADE) as QUANTIDADE FROM
tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = inf.numero
WHERE year(nf.DATA_VENDA) = 2016
GROUP BY tp.sabor, year(nf.DATA_VENDA)
ORDER BY Sum(INF.QUANTIDADE) DESC;


/*QUANTIDADE VENDIDA POR SABOR ANO 2016 */

select * from
(select tp.sabor, year(nf.DATA_VENDA) as ano, sum(INF.QUANTIDADE) as QUANTIDADE FROM
tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = inf.numero
WHERE year(nf.DATA_VENDA) = 2016
GROUP BY tp.sabor, year(nf.DATA_VENDA)) as VENDA_SABOR
inner join
(select year(nf.DATA_VENDA) as ANO, sum(INF.QUANTIDADE) as QUANTIDADE FROM
tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = inf.numero
WHERE year(nf.DATA_VENDA) = 2016
GROUP BY tp.sabor, year(nf.DATA_VENDA)) as VENDA_TOTAL
on VENDA_SABOR.ANO = VENDA_TOTAL.ANO;



SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE,
ROUND((VENDA_SABOR.QUANTIDADE/VENDA_TOTAL.QUANTIDADE) * 100,2) AS PARTICIPACAO FROM 
(SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR
INNER JOIN 
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_SABOR.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_SABOR.QUANTIDADE DESC;



